import { NextPage } from 'next';
import React, { useState } from 'react';
import Head from 'next/head';
import AdminPurchasesTable from '../../modules/dashboard/components/AdminPurchasesTable';

const LoginPage: NextPage = () => {
  const [openMenu, setOpenMenu] = useState(false);

  const handleOpenMenu = () => {
    setOpenMenu(!openMenu);
  };
  return (
    <div>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div
          className="flex h-screen w-full bg-gray-800 "
          x-data="{openMenu:1}"
        >
          <aside className="w-20 relative z-20 flex-shrink-0  px-2 overflow-y-auto bg-indigo-600 sm:block">
            <div className="mb-6">
              <div className="flex justify-center">
                <div className="w-14 h-14 rounded-full bg-gray-300 border-2 border-white mt-2">
                  <img
                    src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQVxhAxJ4D7MOeTTj6kR9PBeZonW5HM7giKjTbEmR-HMBwf3G1VqGnlwpO1kWrdyIZu8_U&usqp=CAU"
                    className="rounded-full w-auto"
                  />
                </div>
              </div>
              <div>
                <ul className="mt-6 leading-10 px-4">
                  <li
                    className="mb-3 p-2 rounded-md flex items-center justify-center bg-blue-400 cursor-pointer text-white"
                    onClick={handleOpenMenu}
                  >
                    {/* <i className="fas fa-align-left fa-sm text-white"></i> */}
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      fill="none"
                      viewBox="0 0 24 24"
                      stroke="currentColor"
                    >
                      <path
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        strokeWidth={2}
                        d="M4 6h16M4 10h16M4 14h16M4 18h16"
                      />
                    </svg>
                  </li>
                  <li className="mb-3 p-2 rounded-md flex items-center justify-center bg-pink-400 cursor-pointer text-white">
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      fill="none"
                      viewBox="0 0 24 24"
                      stroke="currentColor"
                    >
                      <path
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        strokeWidth={2}
                        d="M8.228 9c.549-1.165 2.03-2 3.772-2 2.21 0 4 1.343 4 3 0 1.4-1.278 2.575-3.006 2.907-.542.104-.994.54-.994 1.093m0 3h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"
                      />
                    </svg>
                  </li>
                  <li className="mb-3 p-2 rounded-md flex items-center justify-center bg-yellow-400 cursor-pointer text-white">
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      fill="none"
                      viewBox="0 0 24 24"
                      stroke="currentColor"
                    >
                      <path
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        strokeWidth={2}
                        d="M12 6V4m0 2a2 2 0 100 4m0-4a2 2 0 110 4m-6 8a2 2 0 100-4m0 4a2 2 0 110-4m0 4v2m0-6V4m6 6v10m6-2a2 2 0 100-4m0 4a2 2 0 110-4m0 4v2m0-6V4"
                      />
                    </svg>
                  </li>
                  <li className="absolute bottom-0 mb-3 p-2 rounded-full flex items-center mx-auto bg-white cursor-pointer">
                    <svg
                      version="1.1"
                      id="Layer_1"
                      xmlns="http://www.w3.org/2000/svg"
                      viewBox="0 0 511.996 511.996"
                      width="20px"
                    >
                      <g>
                        <g>
                          <g>
                            <path
                              d="M349.85,62.196c-10.797-4.717-23.373,0.212-28.09,11.009c-4.717,10.797,0.212,23.373,11.009,28.09
                            c69.412,30.324,115.228,98.977,115.228,176.035c0,106.034-85.972,192-192,192c-106.042,0-192-85.958-192-192
                            c0-77.041,45.8-145.694,115.192-176.038c10.795-4.72,15.72-17.298,10.999-28.093c-4.72-10.795-17.298-15.72-28.093-10.999
                            C77.306,99.275,21.331,183.181,21.331,277.329c0,129.606,105.061,234.667,234.667,234.667
                            c129.592,0,234.667-105.068,234.667-234.667C490.665,183.159,434.667,99.249,349.85,62.196z"
                            />
                            <path
                              d="M255.989,234.667c11.782,0,21.333-9.551,21.333-21.333v-192C277.323,9.551,267.771,0,255.989,0
                            c-11.782,0-21.333,9.551-21.333,21.333v192C234.656,225.115,244.207,234.667,255.989,234.667z"
                            />
                          </g>
                        </g>
                      </g>
                    </svg>
                  </li>
                </ul>
              </div>
            </div>
          </aside>
          <aside
            className="animate__animated animate__fadeInLeft w-52 relative z-0 flex-shrink-0 hidden px-4 overflow-y-auto bg-gray-100 sm:block "
            x-show={true}
            style={{ display: openMenu ? 'initial' : 'none' }}
          >
            <div className="mb-6">
              <div className="grid grid-cols-1 gap-4 grid-cols-2 mt-6">
                <div className="p-2 flex flex-col items-center bg-white rounded-md justify-center shadow-xl cursor-pointer">
                  <div className="rounded-full p-2 bg-indigo-200 flex flex-col items-center">
                    <i className="fas fa-chart-pie fa-sm text-indigo-600"></i>
                  </div>
                  <p className="text-xs mt-1 text-center font-semibold">
                    Dashboard
                  </p>
                </div>
                <div className="p-2 flex flex-col items-center bg-white rounded-md justify-center shadow-xl cursor-pointer">
                  <div className="rounded-full p-2 bg-indigo-200 flex flex-col items-center">
                    <i className="fas fa-calculator fa-sm text-indigo-600"></i>
                  </div>
                  <p className="text-xs mt-1 text-center font-semibold">
                    Dashboard
                  </p>
                </div>
              </div>
            </div>
          </aside>

          <div className="flex flex-col flex-1 w-full overflow-y-auto">
            <h1>hola</h1>
            <AdminPurchasesTable />

          </div>
        </div>
      </main>
    </div>
  );
};

export default LoginPage;
